# ########## IoT Platform #################### 
#        Influxdb, NodeRed, Grafana          #  
##############################################

services:

  nodered:
    image: montagny/node-red:latest
    container_name: nodered
    volumes:
     - ./node_data:/data
    ports:
      - "1880:1880"  
      
  influxdb:
    image: influxdb:2.6.1
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=univ-lorawan
      - DOCKER_INFLUXDB_INIT_ORG=training-usmb
      - DOCKER_INFLUXDB_INIT_BUCKET=iot-platform
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=U3lsdmFpbk1vbnRhZ255RXN0VW5DaGFtcGlvbl9Gb3JtYXRpb25Mb1JhV0FOX1VuaXZfU2F2b2llXzIwMjMhCg==
      - TZ=Europe/Paris
    volumes:
      - ./influx_data:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
         
  grafana:
    user: "1000"
    image: grafana/grafana-oss:9.4.3
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=univ-lorawan  
       


